name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Select which job to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - tests
          - deploy

jobs:
#  setup:
#    name: Setup Environment
#    runs-on: ubuntu-latest
#    outputs:
#      python-bin: ${{ steps.python-path.outputs.PYTHON_BIN }}  # Pass Python bin path
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.10"
#
#      - name: Install Poetry
#        run: |
#          curl -sSL https://install.python-poetry.org | python3 -
#          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH
#
#      - name: Install dependencies
#        run: poetry install

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
#    needs: setup
    if: inputs.job == 'all' || inputs.job == 'tests'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH

      - name: Install dependencies
        run: poetry install

      - name: Run Unit Tests
        run: poetry run pytest ./tests -vv

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [tests]
    if: inputs.job == 'all' || inputs.job == 'deploy'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH

      - name: Install dependencies
        run: poetry install

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "${{ secrets.SERVER_DEPLOYMENT_PATH }}"

      - name: Verify Deployment
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ls -lh ${{ secrets.SERVER_DEPLOYMENT_PATH }}
            echo "Deployment successful!"
